### ISSUE TITLE
Click==6.2 still missing for mitmproxy when working with MobSF docker

### ISSUE THREAD

**Issue by 0x4647** [MobSF/CapFuzz#7]
Starting the dynamic analysis with mobsf will throw the following error related to capfuzz saying that 'click<7,>=6.2' is missing in the requirments

* daemon started successfully *
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Click 7.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('click<7,>=6.2'), {'mitmproxy'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/capfuzz", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'click<7,>=6.2' distribution was not found and is required by mitmproxy

**Comment by flamecopper** [comment]
Same here:
raceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Click 7.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('click<7,>=6.2'), {'mitmproxy'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/capfuzz", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'click<7,>=6.2' distribution was not found and is required by mitmproxy
[INFO] 07/Apr/2019 09:07:56 - CapFuzz UI Started
[INFO] 07/Apr/2019 09:08:01 - Dynamic Analysis Report Generation
[INFO] 07/Apr/2019 09:08:01 - Dynamic API Analysis
[INFO] 07/Apr/2019 09:08:01 - Dynamic File Analysis
[INFO] 07/Apr/2019 09:08:01 - Performing Malware Check on extracted Domains
[INFO] 07/Apr/2019 09:08:04 - Malware Database is up-to-date.
[INFO] 07/Apr/2019 09:08:04 - Generating Downloads
[INFO] 07/Apr/2019 09:08:04 - 
Fetching Exported Activity & Activity List from DB
[INFO] 07/Apr/2019 09:08:05 - Starting CapFuzz Web UI
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Click 7.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('click<7,>=6.2'), {'mitmproxy'})

During handling of the above exception, another exception occurred:

**Comment by digininja** [comment]
And the same, installed fresh Docker image a couple of hours ago so bang up to date.
